version: '3.5'

services:
  symfony-api-platform-web:
    container_name: symfony-api-platform-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony-api-platform-be
    networks:
      - symfony-api-platform-network

  symfony-api-platform-be:
    container_name: symfony-api-platform-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      #PHP_IDE_CONFIG: serverName=Docker
      #PHP_XDEBUG_ENABLED: 1
      #XDEBUG_CONFIG: remote_host=172.17.0.1 remote_port=9005 # Linux users
      #XDEBUG_CONFIG: remote_host=kubernetes.docker.internal remote_port=9005 # MacOS users

      # CONFIGURACION PARA XDEBUG 3.x
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
    volumes:
      - ./:/appdata/www
      #- ./docker/php/xdebug-linux.ini:/usr/local/etc/php/conf.d/xdebug.ini
      #- ./docker/php/xdebug-macos.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # Configuracion para xdebug 3.x
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony-api-platform-db
    networks:
      - symfony-api-platform-network

  symfony-api-platform-db:
    container_name: symfony-api-platform-db
    image:  mysql:8.0
    build:
      context: ./docker/database
    ports:
      - 6603:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony-api-platform-db-data:/var/lib/mysql
    networks:
      - symfony-api-platform-network

volumes:
  symfony-api-platform-db-data:

networks:
  symfony-api-platform-network:
    external: true